### ISSUE TITLE
Errors with vitest

### ISSUE THREAD

**Issue by alexcroox** [s00d/nuxt-i18n-micro#77]
**Describe the bug**
I'm struggling to create vitest unit tests for pages/components that use $t

**To Reproduce**
1. Go to 'https://stackblitz.com/edit/github-mag9gj-h2v1xa?file=README.md,app%2Fpages%2Findex.vue,package.json,locales%2Fen-GB.json,nuxt.config.ts,app%2Fcomponents%2FTestComponent.vue,app%2Fcomponents%2FTestComponent.nuxt.spec.ts,tests%2Fvitest.unit-config.ts'
2. Run `npm run test`
4. See errors with loading _locals and $t is not a function

**Screenshots**
```
[nuxt] error caught during app initialization FetchError: [GET] "/_locales/general/en-GB/data.json?v=1733229424546": 404 Cannot find any path matching /_locales/general/en-GB/data.json?v=1733229424546.
    at $fetch2 (file:///home/projects/github-mag9gj-tnstob/node_modules/ofetch/dist/shared/ofetch.03887fc3.mjs:333:15)
    at loadTranslationsForRoute (/home/projects/github-mag9gj-tnstob/node_modules/nuxt-i18n-micro/dist/runtime/plugins/01.plugin.js:232:20)
    at eval (/home/projects/github-mag9gj-tnstob/node_modules/nuxt-i18n-micro/dist/runtime/plugins/01.plugin.js:255:118)
    at applyPlugin (/home/projects/github-mag9gj-tnstob/node_modules/nuxt/dist/app/nuxt.js:146:25)
    at executePlugin (/home/projects/github-mag9gj-tnstob/node_modules/nuxt/dist/app/nuxt.js:183:9)
    at Module.applyPlugins (/home/projects/github-mag9gj-tnstob/node_modules/nuxt/dist/app/nuxt.js:197:5)
    at initApp (/home/projects/github-mag9gj-tnstob/node_modules/nuxt/dist/app/nuxt-vitest-app-entry.js:55:7)
 ```

**Comment by alexcroox** [comment]
OK resolved the missing $t function by mocking it:

```
import { mockNuxtImport } from '@nuxt/test-utils/runtime';
import { type Mock, vi } from 'vitest';

type MockedI18n = {
  $getLocale: () => string;
  $t: Mock;
};

export function createFakeI18n(): MockedI18n {
  return {
    $getLocale: () => 'en-GB',
    $t: vi.fn((...args: unknown[]) =>
      args
        .map((arg) => (typeof arg === 'object' ? JSON.stringify(arg) : arg))
        .join(', ')
    )
  };
}

mockNuxtImport<() => ReturnType<typeof createFakeI18n>>('useI18n', () =>
  vi.fn(() => createFakeI18n())
);
```

I've updated the stackblitz.

Still not sure what to do about the 404 on the json files though "/_locales/general/en-GB/data.json"

**Comment by s00d** [comment]
Hello, I usually test everything through Playwright, and I work with Vitest very rarely. If you could write a couple of simple tests, I will try to prepare a set of test utilities or simply reconfigure the project for testing.

**Comment by alexcroox** [comment]
Sure, here are a few exmaples of different ways I've used vitest before:

https://stackblitz.com/edit/github-mag9gj-h2v1xa?file=app%2Fcomponents%2FTestComponent.nuxt.spec.ts

**Comment by alexcroox** [comment]
wow you are on fire! Thank you so much! I'll test it later this afternoon.

Side note, the new docs contain my example but my excludes config is very specific to my setup so we might want to reduce that to avoid confusing others:

```
export default defineVitestConfig({
  test: {
    setupFiles: ['./tests/unit-setup.ts'],
    include: ['./**/*.spec.ts'],
  },
})
```

**Comment by s00d** [comment]
> wow you are on fire! Thank you so much! I'll test it later this afternoon.
> 
> Side note, the new docs contain my example but my "excludes" config is very specific to my project so we might want to reduce that to avoid confusing others:
> 
> ```
> export default defineVitestConfig({
>   test: {
>     setupFiles: ['./tests/unit-setup.ts'],
>     include: ['./**/*.spec.ts'],
>   },
> })
> ```

fixed. thx

**Comment by s00d** [comment]
Posted update 1.0.1, forgot that postinstall runs during installation, thanks!

**Comment by alexcroox** [comment]
Gave it a test, seems to be working great thanks. Still getting that error but it's not preventing tests from passing:

![SCR-20241205-jfww](https://github.com/user-attachments/assets/98295aee-ecd3-4715-90ce-fb03f167cf5e)

https://stackblitz.com/edit/github-mag9gj-h2v1xa?file=app%2Fcomponents%2FTestComponent.nuxt.spec.ts

run `npm run test` above to see the error

**Comment by s00d** [comment]
try v1.38.4
After deployment, it doesn't recognize `import.meta.env`.

**Comment by alexcroox** [comment]
yeah import.meta.env is a vite runtime/build time thing only works when running/building the app. process.env. otherwise

**Comment by alexcroox** [comment]
Thanks error isn't showing now in latest version!

I noticed this line will fatal error if undefined is accidently passed to $t()

https://github.com/s00d/nuxt-i18n-micro/blob/168f6ac1442634c96f10deca112cca308d8f6fe2/packages/core/src/translation.ts#L31

Maybe it should be:

```
if (translations === null || !key) {
    return null
}
 ```

**Comment by s00d** [comment]
fixed v1.38.5

**Comment by alexcroox** [comment]
All working great, thank you! Loving the library.
